import { isolatedHTML } from './web-artifact.js';
const $ = id => document.getElementById(id);
const ca = () => document.documentElement.lang === 'ca';
const labels = () => ca() ? {title:'Preview',url:'Adreça web',open:'Obre',reload:'Actualitza',external:'Obre externament',close:'Tanca preview',desktop:'Escriptori',mobile:'Mòbil',empty:'Cap web oberta',invalid:'Adreça no vàlida o no permesa',loaded:'Navegació completada',loading:'Carregant',note:'Si la web bloqueja la preview, obre-la externament.',offer:'Obre la web detectada',resize:'Amplada de la preview'} : {title:'Preview',url:'Web address',open:'Open',reload:'Reload',external:'Open externally',close:'Close preview',desktop:'Desktop',mobile:'Mobile',empty:'No website open',invalid:'Invalid or disallowed address',loaded:'Navigation completed',loading:'Loading',note:'If the website blocks the preview, open it externally.',offer:'Open detected website',resize:'Preview width'};
const pane = document.createElement('aside');
pane.id='livePreview';pane.hidden=true;
pane.innerHTML=`<div id="previewDivider" role="separator" tabindex="0" aria-orientation="vertical"></div><header><strong>Preview</strong><button id="previewExternal" type="button">↗</button><button id="previewClose" type="button">×</button></header><form id="previewForm"><input id="previewUrl" type="url" required placeholder="http://localhost:3000"><button id="previewGo" type="submit">→</button><button id="previewReload" type="button">↻</button></form><div class="preview-modes"><button id="previewDesktop" type="button" aria-pressed="true"></button><button id="previewMobile" type="button" aria-pressed="false"></button><button id="previewOffer" type="button" hidden></button></div><div id="previewStatus" role="status"></div><div class="preview-viewport"><iframe id="previewContent" sandbox="allow-scripts allow-forms" referrerpolicy="no-referrer"></iframe><div id="previewEmpty"></div></div><small id="previewNote"></small>`;
$('workbench').append(pane);
const style=document.createElement('style');
style.textContent=`#livePreview[hidden]{display:none}#livePreview{position:relative;flex:0 0 var(--preview-width,480px);width:var(--preview-width,480px);min-width:0;border-left:1px solid var(--line);display:flex;flex-direction:column;background:var(--panel);color:var(--ink);overflow:hidden}#livePreview header,#previewForm,.preview-modes{display:flex;gap:6px;align-items:center;padding:8px 12px}#livePreview header strong{margin-right:auto;font-size:14px}#livePreview button{border:1px solid var(--line-hi);border-radius:4px;background:var(--bg);color:var(--ink);cursor:pointer;padding:6px 9px}#previewForm input{min-width:0;flex:1;border:1px solid var(--line-hi);border-radius:4px;background:var(--bg);color:var(--ink);padding:8px;font:12px monospace}.preview-modes button[aria-pressed=true]{border-color:var(--accent);color:var(--accent)}#previewStatus,#previewNote{padding:6px 12px;color:var(--muted);font-size:11px}.preview-viewport{flex:1;min-height:200px;overflow:auto;background:#dce2e3;position:relative}#previewContent{display:block;width:100%;height:100%;border:0;background:white}#livePreview.mobile-preview #previewContent{width:390px;max-width:100%;margin:auto}#previewEmpty{position:absolute;inset:0;display:grid;place-items:center;background:var(--panel);color:var(--muted)}#previewEmpty[hidden]{display:none}#previewDivider{position:absolute;left:0;top:0;bottom:0;width:6px;cursor:col-resize;z-index:2;touch-action:none}#previewDivider:focus-visible{background:var(--accent)}@media(max-width:1000px){#livePreview{position:fixed;inset:92px 0 0 auto;width:min(100%,560px);z-index:30;box-shadow:-4px 0 16px #0003}#previewDivider{display:none}}`;
document.head.append(style);
let current='',offered='',artifact='';
export function previewURL(raw){
  try{const u=new URL(raw);if(!['http:','https:'].includes(u.protocol)||u.username||u.password||u.origin===location.origin)return null;return u.href;}catch{return null;}
}
function show(on){pane.hidden=!on;$('previewToggle').setAttribute('aria-pressed',String(on));}
function navigate(raw){const url=previewURL(raw);if(!url){$('previewStatus').textContent=labels().invalid;return;}artifact='';current=url;$('previewContent').removeAttribute('srcdoc');$('previewUrl').value=url;$('previewEmpty').hidden=true;$('previewStatus').textContent=labels().loading;$('previewContent').src=url;render();show(true);}
function render(){const l=labels();for(const [id,key] of [['previewUrl','url'],['previewGo','open'],['previewReload','reload'],['previewExternal','external'],['previewClose','close']]){$(id).title=l[key];$(id).setAttribute('aria-label',l[key]);}$('previewContent').title=l.title;$('previewDesktop').textContent=l.desktop;$('previewMobile').textContent=l.mobile;$('previewEmpty').textContent=l.empty;$('previewNote').textContent=artifact?(ca()?'HTML generat · revisa el codi abans de publicar-lo.':'Generated HTML · review the code before publishing.'):l.note;$('previewOffer').textContent=l.offer;$('previewDivider').setAttribute('aria-label',l.resize);$('previewExternal').disabled=!current;}
$('previewToggle').onclick=()=>show(pane.hidden);
$('previewClose').onclick=()=>show(false);
$('previewForm').onsubmit=e=>{e.preventDefault();navigate($('previewUrl').value);};
$('previewReload').onclick=()=>{if(artifact)$('previewContent').srcdoc=isolatedHTML(artifact);else if(current)navigate(current);};
$('previewExternal').onclick=()=>{if(current)window.open(current,'_blank','noopener,noreferrer');};
$('previewContent').onload=()=>{if(current)$('previewStatus').textContent=labels().loaded;};
for(const mobile of [false,true])$(mobile?'previewMobile':'previewDesktop').onclick=()=>{pane.classList.toggle('mobile-preview',mobile);$('previewMobile').setAttribute('aria-pressed',String(mobile));$('previewDesktop').setAttribute('aria-pressed',String(!mobile));};
function width(value){const w=Math.max(320,Math.min(innerWidth*.65,value));pane.style.setProperty('--preview-width',`${w}px`);$('previewDivider').setAttribute('aria-valuenow',String(Math.round(w)));}
$('previewDivider').onpointerdown=e=>{e.preventDefault();e.currentTarget.setPointerCapture(e.pointerId);};
$('previewDivider').onpointermove=e=>{if(e.currentTarget.hasPointerCapture(e.pointerId))width(innerWidth-e.clientX);};
$('previewDivider').onkeydown=e=>{if(['ArrowLeft','ArrowRight'].includes(e.key)){e.preventDefault();width(pane.getBoundingClientRect().width+(e.key==='ArrowLeft'?24:-24));}};
window.gregalPreview={open:navigate,offer(raw){const url=previewURL(raw);if(!url)return;const host=new URL(url).hostname;if(!['localhost','127.0.0.1','[::1]'].includes(host))return;offered=url;$('previewOffer').hidden=false;$('previewOffer').title=url;}};
window.gregalPreview.openHTML=html=>{artifact=html;current='';$('previewUrl').value='';$('previewContent').removeAttribute('src');$('previewContent').srcdoc=isolatedHTML(html);$('previewEmpty').hidden=true;$('previewStatus').textContent=ca()?'Prototip HTML':'HTML prototype';render();show(true);};
$('previewOffer').onclick=()=>navigate(offered);
document.addEventListener('gregal:idioma',render);render();
