package xyz.solanes.gregal

/** Claus només-mòbil (aparellament, cua, avisos...). Manual: la web no les té.
 *  Paritat ca/en a mà, com exigeix la identitat. */
val STR_APP_CA: Map<String, String> = mapOf(
    "app.pair.title" to "Gregal",
    "app.pair.subtitle" to "L'agent de codi de casa, al mòbil",
    "app.pair.host" to "Servidor (IP o nom)",
    "app.pair.user" to "Usuari",
    "app.pair.password" to "Contrasenya",
    "app.pair.login" to "Entra",
    "app.pair.port" to "Port",
    "app.pair.token" to "Token (GREGAL_API_TOKEN)",
    "app.pair.connect" to "Connecta",
    "app.pair.showToken" to "O enganxa un token",
    "app.pair.hideToken" to "Amagar el token",
    "app.nav.menu" to "Menú",
    "app.nav.project" to "Projecte",
    "app.nav.github" to "GitHub (només lectura)",
    "app.nav.undoTurn" to "Desfés els canvis del torn",
    "app.chat.hint" to "Pregunta sobre el projecte…",
    "app.chat.empty" to "Com va tot?",
    "app.chat.working" to "≋ treballant…",
    "app.chat.workingCaps" to "TREBALLANT",
    "app.chat.queued" to "1 petició a la cua · s'enviarà sola",
    "app.chat.attachment" to "@fitxer adjunta context",
    "app.chat.plan" to "◇ Fes-ne un pla",
    "app.chat.planLabel" to "PLA",
    "app.chat.planning" to "PLA · explorant…",
    "app.chat.execute" to "Executa",
    "app.chat.discard" to "Descarta",
    "app.chat.addImage" to "Afegeix imatge",
    "app.chat.dictate" to "Dicta",
    "app.chat.voicePrompt" to "Parla…",
    "app.chat.voiceUnavailable" to "El reconeixement de veu no està disponible en aquest mòbil.",
    "app.chat.send" to "Envia",
    "app.chat.scrollBottom" to "Baixa al final",
    "app.chat.busyNotice" to "≋ Agent ocupat · la teva petició es posarà a la cua",
    "app.chat.queuedNotice" to "⏳ Agent ocupat — he deixat la teva petició a la cua.",
    "app.chat.continueQueued" to "≋ Ara sí — continuo la teva petició.",
    "app.chat.free" to "≋ Lliure — digues.",
    "app.chat.busyTimeout" to "L'agent continua ocupat després de 2 min.",
    "app.chat.compareBusy" to "L'agent està ocupat; espera que acabi abans de comparar models.",
    "app.chat.compareEmpty" to "Cap model ha retornat resposta",
    "app.chat.questionTitle" to "◌ Gregal et pregunta",
    "app.chat.questionFree" to "Resposta lliure",
    "app.chat.questionTimeoutHelp" to "Si no contestes a temps, l'agent continua sol.",
    "app.chat.questionLeave" to "Deixa-ho",
    "app.chat.questionAnswer" to "↩︎ Resposta: %s",
    "app.chat.questionEmpty" to "(buit)",
    "app.chat.questionTimeout" to "◌ La pregunta ha caducat sense resposta.",
    "app.chat.approvalTimeout" to "◌ L'aprovació ha caducat sense resposta.",
    "app.chat.approvalTimeoutDenied" to "◌ L'aprovació ha caducat sense resposta: l'acció s'ha denegat.",
    "app.chat.approvalAllowedAlways" to "🧠 %s · permès sempre (sessió)",
    "app.chat.approvalAllowed" to "✅ %s · permès",
    "app.chat.approvalDenied" to "⛔️ %s · denegat",
    "app.chat.approvalError" to "⚠️ Aprovació: %s",
    "app.chat.approvalNoPayload" to "⚠️ El servidor ha enviat una aprovació sense dades estructurades.",
    "app.chat.questionNoPayload" to "⚠️ El servidor ha enviat una pregunta sense dades estructurades.",
    "app.chat.compactedStatus" to "Conversa compactada (%d → %d missatges)",
    "app.chat.compacted" to "≋ Context compactat automàticament",
    "app.chat.verifyStart" to "Verificant: %s",
    "app.chat.stepsExhausted" to "⚠️ S'han esgotat els %d passos: la feina pot quedar a mitges.",
    "app.chat.toolTextFallback" to "El model ha escrit la crida d'eina com a text: no s'ha executat.",
    "app.chat.fallback" to "↪ Primari caigut · respon %s",
    "app.chat.cancelled" to "⛔️ Torn cancel·lat",
    "app.chat.runQueued" to "En cua…",
    "app.chat.runStarted" to "Treballant…",
    "app.chat.rewindDescription" to "Restaura el contingut d'abans de la sessió (no usa git).",
    "app.chat.rewindEmpty" to "Cap fitxer tocat aquesta sessió.",
    "app.chat.githubTitle" to "GitHub · només lectura",
    "app.chat.githubList" to "Llista",
    "app.chat.githubView" to "Veure",
    "app.chat.githubDiff" to "Diff",
    "app.chat.githubChecks" to "Checks",
    "app.chat.githubNumber" to "Número (opcional)",
    "app.chat.githubSearch" to "Cerca opcional",
    "app.chat.githubRepo" to "owner/repo (opcional)",
    "app.chat.githubRun" to "Consulta",
    "app.chat.retry" to "Torna-hi",
    "app.chat.copied" to "Copiat",
    "app.chat.modeCode" to "◆ Codi",
    "app.chat.modeInspect" to "◉ Consulta (només lectura)",
    "app.chat.modeChat" to "◇ Xat",
    "app.chat.modeGoal" to "◆ Objectiu",
    "app.chat.composerInspect" to "Consulta el projecte, sense modificar res…",
    "app.chat.composerGoal" to "Concreta l'objectiu (no executa)…",
    "app.chat.composerCode" to "Explica què vols fer…",
    "app.modeBadgeCode" to "CODI",
    "app.modeBadgeInspect" to "CONSULTA",
    "app.modeBadgeChat" to "XAT",
    "app.modeBadgeGoal" to "OBJECTIU",
    "app.modeLabelCode" to "Codi",
    "app.modeLabelInspect" to "Consulta",
    "app.modeLabelChat" to "Xat",
    "app.modeLabelGoal" to "Objectiu",
    "app.activity.blocked" to "Activitat · %d accions bloquejades",
    "app.activity.blockedOne" to "Activitat · 1 acció bloquejada",
    "app.activity.tools" to "Eines · %d crides",
    "app.activity.toolsOne" to "Eines · 1 crida",
    "app.activity.steps" to "Activitat · %d passos",
    "app.activity.stepsOne" to "Activitat · 1 pas",
    "app.activity.show" to "Mostra",
    "app.activity.hide" to "Amaga",
    "app.code.copy" to "Copia",
    "app.code.language" to "codi",
    "app.table.moreFiles" to "+ %d files més",
    "app.sess.search" to "Cerca…",
    "app.sess.delete" to "Esborra",
    "app.sess.empty" to "Cap conversa desada",
    "app.sess.oneMessage" to "1 missatge",
    "app.sess.messages" to "%d missatges",
    "app.sess.current" to "actual",
    "app.sess.activeTitle" to "Agent en execució",
    "app.sess.show" to "Veure",
    "app.sess.hide" to "Amaga",
    "app.sess.readOnlyRefresh" to "Només lectura · actualitza cada 3 s",
    "app.sess.noActivity" to "Encara no hi ha activitat rebuda.",
    "app.sess.today" to "Avui",
    "app.sess.yesterday" to "Ahir",
    "app.sess.week" to "Aquesta setmana",
    "app.sess.month" to "Aquest mes",
    "app.sess.older" to "Abans",
    "app.off.title" to "Office",
    "app.off.empty" to "Cap document",
    "app.off.pick" to "Tria un document",
    "app.off.view" to "Vista",
    "app.off.text" to "Text",
    "app.off.ask" to "Demana a l'agent",
    "app.off.download" to "Baixa",
    "app.off.change" to "Canvia de document",
    "app.off.quick.resume" to "Resumeix",
    "app.off.quick.fix" to "Corregeix",
    "app.off.quick.translate" to "Tradueix",
    "app.off.quick.explain" to "Explica les dades",
    "app.off.emptyHelp" to "Puja un .docx, .xlsx o .pptx i demana a l'agent que el resumeixi, corregeixi o tradueixi.",
    "app.off.closeDoc" to "Tanca el document",
    "app.off.document" to "Document",
    "app.off.edit" to "Edita",
    "app.off.sheet" to "Full (p. ex. Dades)",
    "app.off.cell" to "Cel·la (B2)",
    "app.off.value" to "Valor",
    "app.off.setValue" to "Posa valor",
    "app.off.findText" to "Cerca text",
    "app.off.replaceWith" to "Substitueix per",
    "app.off.replace" to "Substitueix",
    "app.off.fileTypeError" to "⚠️ Cal un .docx, .xlsx o .pptx (has triat: %s)",
    "app.off.fileReadError" to "⚠️ No s'ha pogut llegir el fitxer",
    "app.off.fileTooLarge" to "⚠️ Màxim %d MB (el fitxer en fa %d MB)",
    "app.off.fileOpenError" to "⚠️ No s'ha pogut obrir el fitxer: %s",
    "app.off.downloadError" to "⚠️ No s'ha pogut baixar el document",
    "app.off.downloadWriteError" to "⚠️ No s'ha pogut desar el fitxer: %s",
    "app.off.downloadCreateError" to "⚠️ No s'ha pogut crear el fitxer",
    "app.off.downloadSaved" to "✓ Desat a Descàrregues: %s",
    "app.off.uploading" to "Pujant…",
    "app.off.applying" to "Aplicant…",
    "app.off.renderLoading" to "carregant…",
    "app.off.emptySheet" to "(full buit)",
    "app.off.noSlides" to "sense diapos",
    "app.off.renderErrorPrefix" to "No s'ha pogut pintar: ",
    "app.off.renderErrorSuffix" to ". Mira la pestanya Text.",
    "app.off.renderTooLarge" to "Fitxer gros: el pinto en text (%d MB)",
    "app.off.askContext" to "Al document %s (id %s): %s",
    "app.off.quick.findErrors" to "Troba errors",
    "app.off.prompt.xlsxExplain" to "Explica què conté aquest full de càlcul: fulls, columnes i què representen les dades.",
    "app.off.prompt.xlsxErrors" to "Revisa aquest full de càlcul i digue'm cel·les buides, valors sospitosos o incoherències.",
    "app.off.prompt.pptxResume" to "Resumeix aquesta presentació diapositiva a diapositiva.",
    "app.off.prompt.pptxFix" to "Corregeix l'ortografia d'aquesta presentació amb office_edit (op=replace). Digue'm què has canviat.",
    "app.off.prompt.docResume" to "Resumeix aquest document en 5 punts.",
    "app.off.prompt.docFix" to "Corregeix l'ortografia i la gramàtica d'aquest document amb office_edit (op=replace), sense canviar-ne el sentit. Digue'm què has canviat.",
    "app.off.prompt.docTranslate" to "Tradueix aquest document a l'anglès amb office_edit (op=replace), paràgraf a paràgraf.",
    "app.jobs.title" to "Tasques",
    "app.jobs.add" to "Nova tasca",
    "app.jobs.empty" to "Cap tasca",
    "app.jobs.emptyHelp" to "Crea'n una amb el +: notícies diàries, resums o vigilàncies. T'aviso per Telegram quan acabin.",
    "app.jobs.scheduled" to "Programats",
    "app.jobs.recentRuns" to "Últimes execucions",
    "app.jobs.unnamed" to "(sense nom)",
    "app.jobs.next" to "vinent %s",
    "app.jobs.last" to "últim: %s",
    "app.jobs.runNow" to "Ara",
    "app.jobs.more" to "Més",
    "app.jobs.edit" to "Edita",
    "app.jobs.active" to "actiu",
    "app.jobs.paused" to "pausat",
    "app.jobs.done" to "LLEST",
    "app.jobs.error" to "ERROR",
    "app.jobs.newTitle" to "📰 Nova tasca",
    "app.jobs.editTitle" to "📰 Edita la tasca",
    "app.jobs.name" to "Nom",
    "app.jobs.prompt" to "Instruccions per a l'agent",
    "app.jobs.daily" to "Diària",
    "app.jobs.interval" to "Interval",
    "app.jobs.manual" to "Manual",
    "app.jobs.time" to "Hora (HH:MM)",
    "app.jobs.everyHours" to "Cada quantes hores",
    "app.jobs.telegram" to "Avisa per Telegram",
    "app.jobs.emptyJobName" to "(tasca)",
    "app.jobs.everyDayLabel" to "Cada dia %s",
    "app.jobs.everyIntervalLabel" to "Cada %s",
    "app.jobs.doneWord" to "llest",
    "app.jobs.errorWord" to "error",
    "app.jobs.noDetail" to "(sense detall)",
    "app.flow.back" to "Torna",
    "app.flow.steps" to "%d passos",
    "app.flow.input" to "Entrada (opcional)",
    "app.flow.progress" to "Progrés",
    "app.flow.step" to "pas",
    "app.flow.toChat" to "Parla'n al xat",
    "app.goals.title" to "Objectius",
    "app.goals.empty" to "Cap objectiu",
    "app.goals.emptyHelp" to "Demana a l'agent un objectiu en mode Objectiu i aquí el podràs executar.",
    "app.goals.run" to "Executa",
    "app.goals.more" to "Més",
    "app.goals.completed" to "COMPLETAT",
    "app.goals.pending" to "PENDENT",
    "app.notifications.channel" to "Respostes de Gregal",
    "app.notifications.channelDescription" to "Avisa quan Gregal ha acabat una resposta",
    "app.notifications.permissionMissing" to "Sense permís d'avisos, el streaming funciona però no et podré avisar en segon pla.",
    "app.notifications.readyTitle" to "Gregal ha acabat",
    "app.notifications.readyBody" to "Tens una resposta preparada.",
    "app.notifications.workingTitle" to "Gregal està treballant",
    "app.notifications.workingBody" to "Mantinc la connexió mentre arriba la resposta.",
    "app.notifications.you" to "Tu",
    "app.update.channel" to "Actualitzacions",
    "app.update.channelDescription" to "Avisos de versions noves de Gregal",
    "app.update.availableNotification" to "≋ Gregal %s disponible",
    "app.update.tapToUpdate" to "Toca per actualitzar",
    "app.update.downloadedNotification" to "≋ Gregal %s baixada",
    "app.update.tapToInstall" to "Toca per instal·lar-la",
    "app.menu.plan" to "◇ Fes-ne un pla",
    "app.menu.compare" to "◇ Compara models",
    "app.menu.provider" to "Proveïdor",
    "app.menu.loading" to "carregant…",
    "app.menu.providerMissingKey" to "falta clau API — toca per posar-la",
    "app.menu.mode" to "Mode",
    "app.menu.role" to "Rol",
    "app.role.chat" to "per parlar",
    "app.role.think" to "per pensar",
    "app.role.code" to "per programar",
    "app.role.reviewer" to "per revisar",
    "app.menu.model" to "Model (%s)",
    "app.menu.refresh" to "↻ Actualitza",
    "app.menu.keyTitle" to "Clau API · %s",
    "app.menu.keyHelp" to "Enganxa la clau aquí: el servidor l'activa i la pots provar ara mateix.",
    "app.menu.keyMemory" to "La clau només es desa a la memòria del servidor fins que es reiniciï. Per persistir-la, configura ${'$'}{VAR} al fitxer de configuració.",
    "app.menu.keyPlaceholder" to "Clau API",
    "app.menu.keySaved" to "Clau activa fins que es reiniciï el servidor.",
    "app.menu.providerTested" to "L'endpoint respon. Consulta els models disponibles al selector.",
    "app.menu.providerLoadError" to "No s'han pogut carregar els proveïdors: %s",
    "app.menu.providerSaveError" to "No s'ha pogut activar la clau: %s",
    "app.menu.providerTestError" to "No s'ha pogut provar l'endpoint: %s",
    "app.menu.test" to "Prova",
    "app.status.error" to "Error: %s",
    "app.status.loginNoToken" to "El servidor no ha tornat cap token.",
    "app.status.loginInvalid" to "Usuari o contrasenya incorrectes.",
    "app.status.loginFailed" to "No he pogut entrar: %s",
    "app.status.connectionBadToken" to "El token no és correcte. Revisa'l i torna a provar.",
    "app.status.connectionOffline" to "No arribo al servidor. Comprova el Wi-Fi i l'adreça del servidor.",
    "app.status.connectionFailed" to "No he pogut connectar. Torna-ho a provar en uns segons.",
    "app.status.requestBadToken" to "El token ha caducat o no és correcte.",
    "app.status.requestConnection" to "He perdut la connexió amb el servidor. La teva petició no s'ha enviat.",
    "app.status.requestFailed" to "La petició no ha pogut acabar. Torna-ho a provar.",
    "app.status.imageLimit" to "Màxim 3 imatges per torn",
    "app.status.imageType" to "No és una imatge",
    "app.status.imageLarge" to "Imatge massa gran (màxim 8 MB)",
    "app.status.imageRead" to "No he pogut llegir la imatge",
    "app.status.imageError" to "Imatge: %s",
    "app.status.questionSend" to "No s'ha pogut enviar la resposta: %s",
    "app.status.refresh" to "Error: %s",
    "app.status.compareError" to "⚠️ Comparació: %s",
    "app.status.busyTimeout" to "L'agent continua ocupat després de 2 min.",
    "app.status.cancel" to "Cancel·lació: %s",
    "app.status.sessionsLoad" to "Sessions: %s",
    "app.status.sessionHidden" to "La sessió té %d missatges però cap amb text visible (només eines o sistema).",
    "app.status.sessionResume" to "Resume: %s",
    "app.status.sessionNew" to "Nova: %s",
    "app.status.sessionDelete" to "No s'ha pogut esborrar: %s",
    "app.status.checkpoints" to "Checkpoints: %s",
    "app.status.rewind" to "Desfés: %s",
    "app.status.rewindAllDone" to "↩ S'han restaurat tots els canvis.",
    "app.status.rewindToDone" to "↩ Canvis restaurats fins al punt %d.",
    "app.status.modelSelected" to "Model actiu: %s",
    "app.status.modelChange" to "No he pogut canviar de model: %s",
    "app.status.models" to "Models: %s",
    "app.status.planBusy" to "Agent ocupat — espera que acabi per demanar el pla",
    "app.status.planEmpty" to "El model no ha tornat cap pla",
    "app.status.plan" to "Pla: %s",
    "app.status.flows" to "No s'han pogut carregar els grafs: %s",
    "app.status.flowOpen" to "No s'ha pogut obrir el graf: %s",
    "app.status.flowRun" to "El graf no ha pogut córrer: %s",
    "app.status.flowDelete" to "No s'ha pogut esborrar: %s",
    "app.status.goals" to "Objectius: %s",
    "app.status.goalStarted" to "Objectiu en marxa (mode codi)",
    "app.status.goal" to "Goal: %s",
    "app.status.jobs" to "Jobs: %s",
    "app.status.job" to "Job: %s",
    "app.status.jobStarted" to "Job en marxa — t'aviso quan acabi",
    "app.status.runs" to "Execucions: %s",
    "app.status.modelNotConfirmed" to "El servidor no ha confirmat el model seleccionat.",
    "app.status.providers" to "Proveïdors: %s",
    "app.status.providerSaving" to "desant…",
    "app.status.providerTesting" to "provant…",
    "app.update.skipped" to "Silenciada la %s",
    "app.update.current" to "Al dia · %s",
    "app.update.unavailable" to "No s'ha pogut comprovar",
    "app.update.availableStatus" to "Nova versió %s disponible (tens la %s)",
    "app.update.checking" to "Comprovant…",
    "app.update.checkFailed" to "No s'ha pogut comprovar: %s",
    "app.update.downloading" to "Baixant la %s…",
    "app.update.downloadFailed" to "La baixada ha fallat o l'APK no quadra (sha256)",
    "app.update.verified" to "APK verificat · obrint l'instal·lador",
    "app.update.allowUnknown" to "Cal permetre «instal·lar apps desconegudes» per a Gregal",
    "app.update.install" to "Gregal Android %s ja hi és",
    "app.update.currentVersion" to "Tens la %s.",
    "app.update.downloadInstall" to "Baixa i instal·la",
    "app.update.silence" to "Silencia",
    "app.update.later" to "Més tard",
    "app.update.downloadProgress" to "Baixant… %d%%",
    "app.update.shaHelp" to "L'APK es verifica amb sha256 abans d'obrir l'instal·lador.",
    "app.settings.version" to "Versió",
    "app.settings.checkUpdates" to "Comprova actualitzacions",
    "app.time.now" to "ara mateix",
    "app.time.minutes" to "fa %d min",
    "app.time.hours" to "fa %d h",
    "app.time.yesterday" to "ahir",
    "app.tool.title.read" to "Llegir fitxer",
    "app.tool.title.bash" to "Executar comanda",
    "app.tool.title.write" to "Escriure fitxer",
    "app.tool.title.edit" to "Editar fitxer",
    "app.tool.title.search" to "Cercar text",
    "app.tool.title.list" to "Llistar fitxers",
    "app.tool.title.webSearch" to "Cercar a la web",
    "app.tool.title.webFetch" to "Llegir pàgina web",
    "app.tool.title.external" to "Eina externa",
    "app.tool.verb.read" to "Llegirà",
    "app.tool.verb.run" to "Executarà",
    "app.tool.verb.write" to "Escriurà",
    "app.tool.verb.edit" to "Editarà",
    "app.tool.verb.search" to "Cercarà",
    "app.tool.verb.use" to "Farà servir",
    "app.tool.noArgs" to "(sense arguments)",
)

val STR_APP_EN: Map<String, String> = mapOf(
    "app.pair.title" to "Gregal",
    "app.pair.subtitle" to "Your home coding agent, on mobile",
    "app.pair.host" to "Server (IP or name)",
    "app.pair.user" to "Username",
    "app.pair.password" to "Password",
    "app.pair.login" to "Sign in",
    "app.pair.port" to "Port",
    "app.pair.token" to "Token (GREGAL_API_TOKEN)",
    "app.pair.connect" to "Connect",
    "app.pair.showToken" to "Or paste a token",
    "app.pair.hideToken" to "Hide token",
    "app.nav.menu" to "Menu",
    "app.nav.project" to "Project",
    "app.nav.github" to "GitHub (read-only)",
    "app.nav.undoTurn" to "Undo this turn's changes",
    "app.chat.hint" to "Ask about the project…",
    "app.chat.empty" to "How is it going?",
    "app.chat.working" to "≋ working…",
    "app.chat.workingCaps" to "WORKING",
    "app.chat.queued" to "1 request queued · will send itself",
    "app.chat.attachment" to "@file adds context",
    "app.chat.plan" to "◇ Make a plan",
    "app.chat.planLabel" to "PLAN",
    "app.chat.planning" to "PLAN · exploring…",
    "app.chat.execute" to "Run",
    "app.chat.discard" to "Discard",
    "app.chat.addImage" to "Add image",
    "app.chat.dictate" to "Dictate",
    "app.chat.voicePrompt" to "Speak…",
    "app.chat.voiceUnavailable" to "Speech recognition is not available on this device.",
    "app.chat.send" to "Send",
    "app.chat.scrollBottom" to "Scroll to the bottom",
    "app.chat.busyNotice" to "≋ Agent busy · your request will be queued",
    "app.chat.queuedNotice" to "⏳ Agent busy — your request is queued.",
    "app.chat.continueQueued" to "≋ Resuming your request.",
    "app.chat.free" to "≋ Ready — go ahead.",
    "app.chat.busyTimeout" to "The agent is still busy after 2 minutes.",
    "app.chat.compareBusy" to "The agent is busy; wait for it to finish before comparing models.",
    "app.chat.compareEmpty" to "No model returned a response",
    "app.chat.questionTitle" to "◌ Gregal has a question",
    "app.chat.questionFree" to "Your answer",
    "app.chat.questionTimeoutHelp" to "If you don't answer in time, the agent continues on its own.",
    "app.chat.questionLeave" to "Leave blank",
    "app.chat.questionAnswer" to "↩︎ Answer: %s",
    "app.chat.questionEmpty" to "(empty)",
    "app.chat.questionTimeout" to "◌ The question timed out without an answer.",
    "app.chat.approvalTimeout" to "◌ The approval timed out without a response.",
    "app.chat.approvalTimeoutDenied" to "◌ The approval timed out; the action was denied.",
    "app.chat.approvalAllowedAlways" to "🧠 %s · always allowed (session)",
    "app.chat.approvalAllowed" to "✅ %s · allowed",
    "app.chat.approvalDenied" to "⛔️ %s · denied",
    "app.chat.approvalError" to "⚠️ Approval: %s",
    "app.chat.approvalNoPayload" to "⚠️ The server sent an approval without structured data.",
    "app.chat.questionNoPayload" to "⚠️ The server sent a question without structured data.",
    "app.chat.compactedStatus" to "Conversation compacted (%d → %d messages)",
    "app.chat.compacted" to "≋ Context compacted automatically",
    "app.chat.verifyStart" to "Verifying: %s",
    "app.chat.stepsExhausted" to "⚠️ Used all %d steps; the task may be incomplete.",
    "app.chat.toolTextFallback" to "The model returned a tool call as text; it was not run.",
    "app.chat.fallback" to "↪ Primary failed · using %s",
    "app.chat.cancelled" to "⛔️ Run cancelled",
    "app.chat.runQueued" to "Queued…",
    "app.chat.runStarted" to "Working…",
    "app.chat.rewindDescription" to "Restores the contents from before this session (does not use git).",
    "app.chat.rewindEmpty" to "No files changed in this session.",
    "app.chat.githubTitle" to "GitHub · read-only",
    "app.chat.githubList" to "List",
    "app.chat.githubView" to "View",
    "app.chat.githubDiff" to "Diff",
    "app.chat.githubChecks" to "Checks",
    "app.chat.githubNumber" to "Number (optional)",
    "app.chat.githubSearch" to "Optional search",
    "app.chat.githubRepo" to "owner/repo (optional)",
    "app.chat.githubRun" to "Query",
    "app.chat.retry" to "Try again",
    "app.chat.copied" to "Copied",
    "app.chat.modeCode" to "◆ Code",
    "app.chat.modeInspect" to "◉ Inspect (read-only)",
    "app.chat.modeChat" to "◇ Chat",
    "app.chat.modeGoal" to "◆ Goal",
    "app.chat.composerInspect" to "Ask about the project without changing anything…",
    "app.chat.composerGoal" to "Describe the goal (does not run it)…",
    "app.chat.composerCode" to "Describe what you want to do…",
    "app.modeBadgeCode" to "CODE",
    "app.modeBadgeInspect" to "INSPECT",
    "app.modeBadgeChat" to "CHAT",
    "app.modeBadgeGoal" to "GOAL",
    "app.modeLabelCode" to "Code",
    "app.modeLabelInspect" to "Inspect",
    "app.modeLabelChat" to "Chat",
    "app.modeLabelGoal" to "Goal",
    "app.activity.blocked" to "Activity · %d actions blocked",
    "app.activity.blockedOne" to "Activity · 1 action blocked",
    "app.activity.tools" to "Tools · %d calls",
    "app.activity.toolsOne" to "Tools · 1 call",
    "app.activity.steps" to "Activity · %d steps",
    "app.activity.stepsOne" to "Activity · 1 step",
    "app.activity.show" to "Show",
    "app.activity.hide" to "Hide",
    "app.code.copy" to "Copy",
    "app.code.language" to "code",
    "app.table.moreFiles" to "+ %d more files",
    "app.sess.search" to "Search…",
    "app.sess.delete" to "Delete",
    "app.sess.empty" to "No saved conversations",
    "app.sess.oneMessage" to "1 message",
    "app.sess.messages" to "%d messages",
    "app.sess.current" to "current",
    "app.sess.activeTitle" to "Agent running",
    "app.sess.show" to "View",
    "app.sess.hide" to "Hide",
    "app.sess.readOnlyRefresh" to "Read-only · refreshes every 3 s",
    "app.sess.noActivity" to "No activity received yet.",
    "app.sess.today" to "Today",
    "app.sess.yesterday" to "Yesterday",
    "app.sess.week" to "This week",
    "app.sess.month" to "This month",
    "app.sess.older" to "Older",
    "app.off.title" to "Office",
    "app.off.empty" to "No document",
    "app.off.pick" to "Pick a document",
    "app.off.view" to "View",
    "app.off.text" to "Text",
    "app.off.ask" to "Ask the agent",
    "app.off.download" to "Download",
    "app.off.change" to "Switch document",
    "app.off.quick.resume" to "Summarise",
    "app.off.quick.fix" to "Proofread",
    "app.off.quick.translate" to "Translate",
    "app.off.quick.explain" to "Explain the data",
    "app.off.emptyHelp" to "Upload a .docx, .xlsx, or .pptx file and ask the agent to summarise, proofread, or translate it.",
    "app.off.closeDoc" to "Close document",
    "app.off.document" to "Document",
    "app.off.edit" to "Edit",
    "app.off.sheet" to "Sheet (e.g. Data)",
    "app.off.cell" to "Cell (B2)",
    "app.off.value" to "Value",
    "app.off.setValue" to "Set value",
    "app.off.findText" to "Find text",
    "app.off.replaceWith" to "Replace with",
    "app.off.replace" to "Replace",
    "app.off.fileTypeError" to "⚠️ Choose a .docx, .xlsx, or .pptx file (selected: %s)",
    "app.off.fileReadError" to "⚠️ Could not read the file",
    "app.off.fileTooLarge" to "⚠️ Maximum %d MB (this file is %d MB)",
    "app.off.fileOpenError" to "⚠️ Could not open the file: %s",
    "app.off.downloadError" to "⚠️ Could not download the document",
    "app.off.downloadWriteError" to "⚠️ Could not save the file: %s",
    "app.off.downloadCreateError" to "⚠️ Could not create the file",
    "app.off.downloadSaved" to "✓ Saved to Downloads: %s",
    "app.off.uploading" to "Uploading…",
    "app.off.applying" to "Applying…",
    "app.off.renderLoading" to "Loading…",
    "app.off.emptySheet" to "(empty sheet)",
    "app.off.noSlides" to "No slides",
    "app.off.renderErrorPrefix" to "Could not render: ",
    "app.off.renderErrorSuffix" to ". Switch to Text view.",
    "app.off.renderTooLarge" to "File too large; showing text instead (%d MB)",
    "app.off.askContext" to "About document %s (id %s): %s",
    "app.off.quick.findErrors" to "Find issues",
    "app.off.prompt.xlsxExplain" to "Explain this spreadsheet: its sheets, columns, and what the data represents.",
    "app.off.prompt.xlsxErrors" to "Review this spreadsheet and identify blank cells, suspicious values, or inconsistencies.",
    "app.off.prompt.pptxResume" to "Summarise this presentation slide by slide.",
    "app.off.prompt.pptxFix" to "Proofread this presentation with office_edit (op=replace). Tell me what you changed.",
    "app.off.prompt.docResume" to "Summarise this document in five bullet points.",
    "app.off.prompt.docFix" to "Proofread this document with office_edit (op=replace), preserving its meaning. Tell me what you changed.",
    "app.off.prompt.docTranslate" to "Translate this document into English with office_edit (op=replace), paragraph by paragraph.",
    "app.jobs.title" to "Jobs",
    "app.jobs.add" to "New job",
    "app.jobs.empty" to "No jobs",
    "app.jobs.emptyHelp" to "Create one with +: daily news, summaries, or monitors. I'll notify you on Telegram when they finish.",
    "app.jobs.scheduled" to "Scheduled",
    "app.jobs.recentRuns" to "Recent runs",
    "app.jobs.unnamed" to "(untitled)",
    "app.jobs.next" to "next %s",
    "app.jobs.last" to "last: %s",
    "app.jobs.runNow" to "Run now",
    "app.jobs.more" to "More",
    "app.jobs.edit" to "Edit",
    "app.jobs.active" to "active",
    "app.jobs.paused" to "paused",
    "app.jobs.done" to "DONE",
    "app.jobs.error" to "ERROR",
    "app.jobs.newTitle" to "📰 New job",
    "app.jobs.editTitle" to "📰 Edit job",
    "app.jobs.name" to "Name",
    "app.jobs.prompt" to "Instructions for the agent",
    "app.jobs.daily" to "Daily",
    "app.jobs.interval" to "Interval",
    "app.jobs.manual" to "Manual",
    "app.jobs.time" to "Time (HH:MM)",
    "app.jobs.everyHours" to "Every how many hours",
    "app.jobs.telegram" to "Notify via Telegram",
    "app.jobs.emptyJobName" to "(job)",
    "app.jobs.everyDayLabel" to "Every day %s",
    "app.jobs.everyIntervalLabel" to "Every %s",
    "app.jobs.doneWord" to "done",
    "app.jobs.errorWord" to "error",
    "app.jobs.noDetail" to "(no details)",
    "app.flow.back" to "Back",
    "app.flow.steps" to "%d steps",
    "app.flow.input" to "Input (optional)",
    "app.flow.progress" to "Progress",
    "app.flow.step" to "step",
    "app.flow.toChat" to "Continue in chat",
    "app.goals.title" to "Goals",
    "app.goals.empty" to "No goals",
    "app.goals.emptyHelp" to "Ask the agent to define a goal in Goal mode, then run it here.",
    "app.goals.run" to "Run",
    "app.goals.more" to "More",
    "app.goals.completed" to "COMPLETED",
    "app.goals.pending" to "PENDING",
    "app.notifications.channel" to "Gregal responses",
    "app.notifications.channelDescription" to "Notifies you when Gregal finishes a response",
    "app.notifications.permissionMissing" to "Without notification permission, streaming still works, but I cannot notify you in the background.",
    "app.notifications.readyTitle" to "Gregal has finished",
    "app.notifications.readyBody" to "A response is ready.",
    "app.notifications.workingTitle" to "Gregal is working",
    "app.notifications.workingBody" to "Keeping the connection alive while the response arrives.",
    "app.notifications.you" to "You",
    "app.update.channel" to "Updates",
    "app.update.channelDescription" to "Notifications about new Gregal versions",
    "app.update.availableNotification" to "≋ Gregal %s is available",
    "app.update.tapToUpdate" to "Tap to update",
    "app.update.downloadedNotification" to "≋ Gregal %s downloaded",
    "app.update.tapToInstall" to "Tap to install",
    "app.menu.plan" to "◇ Make a plan",
    "app.menu.compare" to "◇ Compare models",
    "app.menu.provider" to "Provider",
    "app.menu.loading" to "Loading…",
    "app.menu.providerMissingKey" to "API key missing — tap to add one",
    "app.menu.mode" to "Mode",
    "app.menu.role" to "Role",
    "app.role.chat" to "for conversation",
    "app.role.think" to "for reasoning",
    "app.role.code" to "for coding",
    "app.role.reviewer" to "for review",
    "app.menu.model" to "Model (%s)",
    "app.menu.refresh" to "↻ Refresh",
    "app.menu.keyTitle" to "API key · %s",
    "app.menu.keyHelp" to "Paste the key here; the server activates it and you can test it now.",
    "app.menu.keyMemory" to "The key stays in server memory until restart. To persist it, configure ${'$'}{VAR} in the config file.",
    "app.menu.keyPlaceholder" to "API key",
    "app.menu.keySaved" to "Key active until the server restarts.",
    "app.menu.providerTested" to "The endpoint responded. Use the model picker to see available models.",
    "app.menu.providerLoadError" to "Could not load providers: %s",
    "app.menu.providerSaveError" to "Could not activate the key: %s",
    "app.menu.providerTestError" to "Could not test the endpoint: %s",
    "app.menu.test" to "Test",
    "app.status.error" to "Error: %s",
    "app.status.loginNoToken" to "The server did not return a token.",
    "app.status.loginInvalid" to "Incorrect username or password.",
    "app.status.loginFailed" to "Could not sign in: %s",
    "app.status.connectionBadToken" to "The token is incorrect. Check it and try again.",
    "app.status.connectionOffline" to "Couldn't reach the server. Check Wi-Fi and the server address.",
    "app.status.connectionFailed" to "Could not connect. Try again in a few seconds.",
    "app.status.requestBadToken" to "The token has expired or is incorrect.",
    "app.status.requestConnection" to "The connection to the server was lost. Your request was not sent.",
    "app.status.requestFailed" to "The request could not finish. Try again.",
    "app.status.imageLimit" to "Maximum 3 images per turn",
    "app.status.imageType" to "This is not an image",
    "app.status.imageLarge" to "Image too large (maximum 8 MB)",
    "app.status.imageRead" to "Could not read the image",
    "app.status.imageError" to "Image: %s",
    "app.status.questionSend" to "Could not send the answer: %s",
    "app.status.refresh" to "Error: %s",
    "app.status.compareError" to "⚠️ Comparison: %s",
    "app.status.busyTimeout" to "The agent is still busy after 2 minutes.",
    "app.status.cancel" to "Cancel: %s",
    "app.status.sessionsLoad" to "Sessions: %s",
    "app.status.sessionHidden" to "The session has %d messages, but none have visible text (only tools or system messages).",
    "app.status.sessionResume" to "Resume: %s",
    "app.status.sessionNew" to "New session: %s",
    "app.status.sessionDelete" to "Could not delete: %s",
    "app.status.checkpoints" to "Checkpoints: %s",
    "app.status.rewind" to "Undo: %s",
    "app.status.rewindAllDone" to "↩ All changes restored.",
    "app.status.rewindToDone" to "↩ Changes restored to checkpoint %d.",
    "app.status.modelSelected" to "Active model: %s",
    "app.status.modelChange" to "Could not change model: %s",
    "app.status.models" to "Models: %s",
    "app.status.planBusy" to "The agent is busy; wait for it to finish before asking for a plan.",
    "app.status.planEmpty" to "The model returned no plan",
    "app.status.plan" to "Plan: %s",
    "app.status.flows" to "Could not load graphs: %s",
    "app.status.flowOpen" to "Could not open graph: %s",
    "app.status.flowRun" to "Could not run graph: %s",
    "app.status.flowDelete" to "Could not delete graph: %s",
    "app.status.goals" to "Goals: %s",
    "app.status.goalStarted" to "Goal started (code mode)",
    "app.status.goal" to "Goal: %s",
    "app.status.jobs" to "Jobs: %s",
    "app.status.job" to "Job: %s",
    "app.status.jobStarted" to "Job started — I'll notify you when it finishes",
    "app.status.runs" to "Runs: %s",
    "app.status.modelNotConfirmed" to "The server did not confirm the selected model.",
    "app.status.providers" to "Providers: %s",
    "app.status.providerSaving" to "Saving…",
    "app.status.providerTesting" to "Testing…",
    "app.update.skipped" to "Skipped %s",
    "app.update.current" to "Up to date · %s",
    "app.update.unavailable" to "Could not check for updates",
    "app.update.availableStatus" to "Gregal %s is available (you have %s)",
    "app.update.checking" to "Checking…",
    "app.update.checkFailed" to "Could not check: %s",
    "app.update.downloading" to "Downloading %s…",
    "app.update.downloadFailed" to "Download failed or the APK did not match its SHA-256 checksum",
    "app.update.verified" to "APK verified · opening installer",
    "app.update.allowUnknown" to "Allow Gregal to install unknown apps in system settings",
    "app.update.install" to "Gregal Android %s is available",
    "app.update.currentVersion" to "You have %s.",
    "app.update.downloadInstall" to "Download and install",
    "app.update.silence" to "Skip this version",
    "app.update.later" to "Later",
    "app.update.downloadProgress" to "Downloading… %d%%",
    "app.update.shaHelp" to "The APK is checked against its SHA-256 checksum before opening the installer.",
    "app.settings.version" to "Version",
    "app.settings.checkUpdates" to "Check for updates",
    "app.time.now" to "just now",
    "app.time.minutes" to "%d min ago",
    "app.time.hours" to "%d h ago",
    "app.time.yesterday" to "yesterday",
    "app.tool.title.read" to "Read file",
    "app.tool.title.bash" to "Run command",
    "app.tool.title.write" to "Write file",
    "app.tool.title.edit" to "Edit file",
    "app.tool.title.search" to "Search text",
    "app.tool.title.list" to "List files",
    "app.tool.title.webSearch" to "Search the web",
    "app.tool.title.webFetch" to "Read web page",
    "app.tool.title.external" to "External tool",
    "app.tool.verb.read" to "Will read",
    "app.tool.verb.run" to "Will run",
    "app.tool.verb.write" to "Will write",
    "app.tool.verb.edit" to "Will edit",
    "app.tool.verb.search" to "Will search",
    "app.tool.verb.use" to "Will use",
    "app.tool.noArgs" to "(no arguments)",
)

/** Les dues taules han de tenir les mateixes claus (com a la web). */
fun appStringsOk(): Boolean = STR_APP_CA.keys == STR_APP_EN.keys

/** Text d'interfície en l'idioma actiu. Les claus app.* (només mòbil) van
 *  primer; la resta cauen a les taules generades de la web (Strings.kt). */
fun tr(lang: String, key: String, vararg args: Any?): String {
    val app = (if (lang == "en") STR_APP_EN else STR_APP_CA)[key]
    val value = app ?: (if (lang == "en") STR_EN else STR_CA)[key] ?: STR_CA[key] ?: key
    return if (args.isEmpty()) value else String.format(java.util.Locale.ROOT, value, *args)
}
