// Generat des d'internal/web/app/i18n.js — NO EDITAR A MÀ.
// Paritat ca/en amb la web. Regenera amb: python3 android/regen-strings.py
package xyz.solanes.gregal

val STR_CA: Map<String, String> = mapOf(
    "btn.allow" to "Permet",
    "btn.close" to "Tanca",
    "btn.copy" to "Copia el text",
    "btn.delete" to "Esborra",
    "btn.deny" to "Denega",
    "btn.disconnect" to "Desconnecta",
    "btn.new" to "Nou",
    "btn.open" to "Obre…",
    "btn.retry" to "Torna a demanar-ho",
    "btn.run" to "Executa",
    "btn.save" to "Desa",
    "btn.send" to "Envia",
    "btn.stop" to "Atura",
    "btn.toBottom" to "Ves al final",
    "composer.attach" to "Adjunta",
    "composer.hint" to "@fitxer adjunta context · Maj+Enter nova línia",
    "composer.ph" to "Descriu el canvi que vols fer…",
    "composer.ph.chat" to "Pregunta sobre el projecte…",
    "composer.ph.goal" to "Explica què vols aconseguir; et faré les preguntes que calguin…",
    "graphs.agent" to "Agent",
    "graphs.auto" to "sense demanar permís",
    "graphs.auto.help" to "Un graf corre sol i no hi ha ningú per contestar el diàleg de permisos. Les eines denegades continuen bloquejades.",
    "graphs.desc.ph" to "Per a què serveix",
    "graphs.empty" to "Comença amb un pas d'Agent o d'Eina de l'esquerra. Arrossega des del punt de sota d'un pas fins a un altre per connectar-los, i clica la fletxa per dir quan s'agafa.",
    "graphs.lead" to "Un procediment dibuixat. Es desa al projecte i viatja amb el repositori.",
    "graphs.name.ph" to "Nom del graf",
    "graphs.note" to "Nota",
    "graphs.saved" to "Desats",
    "graphs.title" to "Grafs",
    "graphs.tool" to "Eina",
    "keys.title" to "Dreceres",
    "nav.activity" to "Activitat",
    "nav.changes" to "Canvis",
    "nav.convs" to "Converses",
    "nav.files" to "Fitxers",
    "nav.goals" to "Objectius",
    "nav.graphs" to "Grafs",
    "nav.new" to "Nova sessió",
    "nav.office" to "Office",
    "nav.project" to "Projecte actual",
    "nav.search" to "Cerca…",
    "nav.terminal" to "Terminal",
    "nav.tools" to "Eines",
    "nav.workspace" to "Workspace",
    "prefs.agent" to "Agent",
    "prefs.appearance" to "Aparença",
    "prefs.conversation" to "Conversa",
    "prefs.density" to "Densitat",
    "prefs.density.compact" to "Compacta",
    "prefs.density.cosy" to "Còmoda",
    "prefs.density.help" to "Quant aire hi ha entre missatges.",
    "prefs.density.normal" to "Normal",
    "prefs.detail" to "Detall",
    "prefs.detail.help" to "Què es veu de la feina de l'agent.",
    "prefs.detail.summary" to "Resum",
    "prefs.detail.verbose" to "Detallada",
    "prefs.lang" to "Idioma",
    "prefs.lang.help" to "De la finestra i de les respostes de l'agent.",
    "prefs.perms" to "Permisos",
    "prefs.perms.accept" to "Accepta edicions",
    "prefs.perms.auto" to "Auto",
    "prefs.perms.help" to "Què pot fer sense preguntar.",
    "prefs.perms.manual" to "Manual",
    "prefs.providers" to "Proveïdors i models",
    "prefs.providers.help" to "Afegeix proveïdors i tria quin model fa servir cada rol.",
    "prefs.providers.row" to "Endpoints i rols",
    "prefs.size" to "Mida del text",
    "prefs.size.large" to "Gran",
    "prefs.size.small" to "Petita",
    "prefs.theme" to "Tema",
    "prefs.theme.dark" to "Fosc",
    "prefs.theme.help" to "El TUI és sempre fosc; això és per a la finestra.",
    "prefs.theme.light" to "Clar",
    "prefs.theme.system" to "Sistema",
    "prefs.title" to "Preferències",
    "prefs.verify" to "Revisor automàtic",
    "prefs.verify.help" to "Passa un segon model per sobre de cada resposta. Apagat, el pots demanar quan vulguis.",
    "rewind.all" to "Desfés-ho tot",
    "rewind.title" to "Desfés canvis",
)

val STR_EN: Map<String, String> = mapOf(
    "btn.allow" to "Allow",
    "btn.close" to "Close",
    "btn.copy" to "Copy text",
    "btn.delete" to "Delete",
    "btn.deny" to "Deny",
    "btn.disconnect" to "Disconnect",
    "btn.new" to "New",
    "btn.open" to "Open…",
    "btn.retry" to "Ask again",
    "btn.run" to "Run",
    "btn.save" to "Save",
    "btn.send" to "Send",
    "btn.stop" to "Stop",
    "btn.toBottom" to "Go to the end",
    "composer.attach" to "Attach",
    "composer.hint" to "@file adds context · Shift+Enter for a new line",
    "composer.ph" to "Describe the change you want…",
    "composer.ph.chat" to "Ask about the project…",
    "composer.ph.goal" to "Explain what you want to achieve; I'll ask what I need…",
    "graphs.agent" to "Agent",
    "graphs.auto" to "without asking permission",
    "graphs.auto.help" to "A graph runs on its own and nobody is there to answer the permission dialog. Denied tools stay blocked.",
    "graphs.desc.ph" to "What it is for",
    "graphs.empty" to "Start with an Agent or Tool step from the left. Drag from the dot under a step to another one to connect them, and click the arrow to say when it is taken.",
    "graphs.lead" to "A procedure, drawn. It is saved in the project and travels with the repository.",
    "graphs.name.ph" to "Graph name",
    "graphs.note" to "Note",
    "graphs.saved" to "Saved",
    "graphs.title" to "Graphs",
    "graphs.tool" to "Tool",
    "keys.title" to "Shortcuts",
    "nav.activity" to "Activity",
    "nav.changes" to "Changes",
    "nav.convs" to "Conversations",
    "nav.files" to "Files",
    "nav.goals" to "Goals",
    "nav.graphs" to "Graphs",
    "nav.new" to "New session",
    "nav.office" to "Office",
    "nav.project" to "Current project",
    "nav.search" to "Search…",
    "nav.terminal" to "Terminal",
    "nav.tools" to "Tools",
    "nav.workspace" to "Workspace",
    "prefs.agent" to "Agent",
    "prefs.appearance" to "Appearance",
    "prefs.conversation" to "Conversation",
    "prefs.density" to "Density",
    "prefs.density.compact" to "Compact",
    "prefs.density.cosy" to "Roomy",
    "prefs.density.help" to "How much air there is between messages.",
    "prefs.density.normal" to "Normal",
    "prefs.detail" to "Detail",
    "prefs.detail.help" to "How much of the agent's work you see.",
    "prefs.detail.summary" to "Summary",
    "prefs.detail.verbose" to "Verbose",
    "prefs.lang" to "Language",
    "prefs.lang.help" to "For the window and for the agent's answers.",
    "prefs.perms" to "Permissions",
    "prefs.perms.accept" to "Accept edits",
    "prefs.perms.auto" to "Auto",
    "prefs.perms.help" to "What it may do without asking.",
    "prefs.perms.manual" to "Manual",
    "prefs.providers" to "Providers and models",
    "prefs.providers.help" to "Add providers and pick which model each role uses.",
    "prefs.providers.row" to "Endpoints and roles",
    "prefs.size" to "Text size",
    "prefs.size.large" to "Large",
    "prefs.size.small" to "Small",
    "prefs.theme" to "Theme",
    "prefs.theme.dark" to "Dark",
    "prefs.theme.help" to "The TUI is always dark; this is for the window.",
    "prefs.theme.light" to "Light",
    "prefs.theme.system" to "System",
    "prefs.title" to "Preferences",
    "prefs.verify" to "Automatic reviewer",
    "prefs.verify.help" to "Runs a second model over every answer. Switched off, you can still ask for it.",
    "rewind.all" to "Undo all",
    "rewind.title" to "Undo changes",
)
